server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
  #      max-request-size: 10240KB #?? ?? ??? : 10MB
  #      max-file-size: 10240KB #?? ?? ??? : 10MB

#  redis:
#    lettuce:
#      pool:
#        max-active: 5 # pool에 할당될 수 있는 커넥션 최대수
#        max-idle: 5 # pool의 'idle' 커넥션 최대수
#        min-idle: 2
#    host: localhost
#    port: 6370

logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    kr.weareboard.werewolf.api: debug
#    org:
#      hibernate:
#        sql: debug # debug로 하지 않으면 debug, info log 2개씩 나오게 됨
#        tool.hbm2ddl: debug
#        type.descriptor.sql: trace # Hibernate 4,5
#        orm.jdbc.bind: trace # Hibernate 6

auth:
  kakao:
    key:
      admin: a9d0e932ded3f126dc0a52bd275ee73d

storage:
  prefix: files
# storage location은 profiles별로 설정
#  location: files

springdoc:
  version: 1.0.2
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
    persist-authorization: true
  paths-to-match:
    - /api/**

---
spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://werewolf.weareboard.kr/dev/login/oauth2/code/kakao # 성공 시 리다이렉트 URL 지정 값과 맞춰야 한다.  /login/oauth2/code/kakao는 고정이다.
            client-id: a9d0e932ded3f126dc0a52bd275ee73d # REST API 키
            client-secret: 5Symp8XFMgqwkyFCmVlUh4ZKwrUTlrGO # 카카오 로그인 > 보안 > Client-Secret
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  port: 53103

logging:
  config: classpath:logback-spring.xml

auth:
  kakao:
    login:
      redirect:
        url: https://plz-front-highjoon.vercel.app
    logout:
      redirect:
        url: http://localhost:3000

storage:
  location: D:/weareboard_files/lp/files
  # 마지막 /는 필수입니다.
  filePath: file:////D:/weareboard_files/lp/files/

---
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:53101/login/oauth2/code/kakao
            client-id: a9d0e932ded3f126dc0a52bd275ee73d # REST API 키
            client-secret: 5Symp8XFMgqwkyFCmVlUh4ZKwrUTlrGO # 카카오 로그인 > 보안 > Client-Secret
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
server:
  port: 53101

auth:
  kakao:
    login:
      redirect:
        url: http://localhost:5173
    logout:
      redirect:
        url: http://localhost:53101

storage:
  location: D:/git/LP-PLAYLIST-BACKEND/files
  # 마지막 /는 필수입니다.
  filePath: file:////D:/git/LP-PLAYLIST-BACKEND/files/



---
spring:
  config:
    activate:
      on-profile: "proddb"
  datasource:
    url: jdbc:mariadb://localhost:58306/werewolf?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
    username: root
    #        password: 1234
    password: leehj12!$
    #    url: jdbc:mariadb://14.45.108.75:3306/laundry?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
    #    username: laundry
    #    password: jsolwpdlthffntus750!@
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://lp.weareboard.kr/login/oauth2/code/kakao
---
spring:
  config:
    activate:
      on-profile: "localdb"

  datasource:
    url: jdbc:mariadb://localhost:58306/werewolf?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
    username: root
    #    password: 1234
    password: leehj12!$
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: false

#            redirect-uri: https://werewolf.weareboard.kr/dev/login/oauth2/code/kakao # 성공 시 리다이렉트 URL 지정 값과 맞춰야 한다.  /login/oauth2/code/kakao는 고정이다.

