spring:
    datasource:
        url: jdbc:mariadb://hellbot_mariadb:3306/werewolf?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
        username: hellbot
        #        password: 1234
        password: leehj124!!!$
        #    url: jdbc:mariadb://14.45.108.75:3306/laundry?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
        #    username: laundry
        #    password: jsolwpdlthffntus750!@
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                show_sql: false
server:
    port: 53103

logging:
    config: classpath:logback-spring.xml

auth:
    kakao:
        login:
            redirect:
                url: https://plz-front-highjoon.vercel.app
        logout:
            redirect:
                url: http://localhost:3000

storage:
    location: D:/weareboard_files/lp/files
    # 마지막 /는 필수입니다.
    filePath: file:////D:/weareboard_files/lp/files/
