spring:
    datasource:
        url: jdbc:mariadb://43.200.154.185:10101/hellbot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
        username: hellbot
        password: leehj124!!!$
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
                show_sql: false

server:
    port: 40100

logging:
    level:
        org.springframework.web: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type: TRACE
