spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:53101/login/oauth2/code/kakao
            client-id: a9d0e932ded3f126dc0a52bd275ee73d # REST API 키
            client-secret: 5Symp8XFMgqwkyFCmVlUh4ZKwrUTlrGO # 카카오 로그인 > 보안 > Client-Secret
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
server:
  port: 53101

auth:
  kakao:
    login:
      redirect:
        url: http://localhost:5173
    logout:
      redirect:
        url: http://localhost:53101

storage:
  location: D:/git/LP-PLAYLIST-BACKEND/files
  # 마지막 /는 필수입니다.
  filePath: file:////D:/git/LP-PLAYLIST-BACKEND/files/
