spring:
    datasource:
        url: jdbc:mariadb://hellbot_mariadb:3306/hellbot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
        username: hellbot
        password: leehj124!!!$
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                show_sql: false
server:
    port: 53103

logging:
    config: classpath:logback-spring.xml
#    level:
#        org.springframework.web: INFO
#        org.hibernate.SQL: DEBUG
#        org.hibernate.type: TRACE
storage:
    location: D:/weareboard_files/lp/files
    # 마지막 /는 필수입니다.
    filePath: file:////D:/weareboard_files/lp/files/
